version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    command: bash -c "cd /app && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
